import Head from "next/head";
import Profile from "../src/components/left-sidebar/profile";
import Menu from "../src/components/left-sidebar/menu";
import Logout from "../src/components/left-sidebar/logout";
import Search from "../src/components/main/search";
import Overview from "../src/components/main/overview";
import Consultations from "../src/components/right-bar/consultations";
import Sync from "../src/components/right-bar/sync";
import GetConsultant from "../src/components/right-bar/get-consultant";
import Prescribed from "../src/components/main/prescibed";
import { HiBars3, HiOutlineXMark } from "react-icons/hi2";
import { useEffect, useState } from "react";
import useWindowDimensions from "../src/utils/useWindowDimension";

export default function Home() {
  const [showLeftSidebar, setShowLeftSidebar] = useState<boolean>(false);
  const { width, height } = useWindowDimensions();

  useEffect(() => {
    if (width > 1024) {
      setShowLeftSidebar(true);
    }
  }, [width]);

  return (
    <>
      <Head>
        <title>Health App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Mobile menu */}
      <div className="fixed z-30 top-1 left-0 rounded-md right-0 block lg:hidden bg-orange-500 w-[calc(100%-.25rem)] mx-auto  p-4">
        <div className="flex">
          {showLeftSidebar ? (
            <HiOutlineXMark
              className="w-6 h-6 text-white cursor-pointer"
              onClick={() => setShowLeftSidebar(!showLeftSidebar)}
            />
          ) : (
            <HiBars3
              className="w-6 h-6 fill-white cursor-pointer"
              onClick={() => setShowLeftSidebar(!showLeftSidebar)}
            />
          )}
        </div>
      </div>
      <div className="2xl:container mx-auto flex gap-10 p-0 lg:p-0">
        <div
          className={`sidebar h-screen  py-12 flex flex-col z-20 fixed w-[260px] overflow-y-auto ${
            showLeftSidebar ? "opacity-100" : "opacity-0"
          }`}
        >
          <Profile />
          <Menu />
          <Logout />
        </div>
        <div className="w-full grid grid-cols-12 lg:gap-x-10 gap-x-0 ml-0 lg:ml-[300px] p-4 lg:p-0">
          <div className="lg:col-span-9 col-span-12">
            <div className="main h-full pt-5 mt-8 lg:mt-0">
              <Search />
              <Overview />
            </div>
          </div>
          <div
            className={`right-bar col-span-12 lg:col-span-3 lg:pr-10 lg:block mt-0`}
          >
            <GetConsultant />
            <Sync />
            <Consultations />
          </div>
          <div className="col-span-12">
            <Prescribed />
          </div>
        </div>
      </div>
    </>
  );
}
